# Generated by Django 5.2.12 on 2026-03-20 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SplitIt', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='delivery_fee',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='pickup_location',
            field=models.CharField(default='미정', max_length=100),
        ),
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('모집중', '모집중'), ('모집완료', '모집완료')], default='모집중', max_length=10),
        ),
        migrations.AddField(
            model_name='post',
            name='store_name',
            field=models.CharField(default='미정', max_length=100),
        ),
        migrations.AddField(
            model_name='post',
            name='target_headcount',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='post',
            name='writer',
            field=models.CharField(default='익명', max_length=50),
        ),
    ]
