# Generated by Django 5.2.12 on 2026-05-14 06:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SplitIt', '0004_post_photo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='username',
        ),
        migrations.AddField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('한식', '한식'), ('분식', '분식'), ('양식', '양식'), ('중식', '중식'), ('일식', '일식'), ('샐러드', '샐러드'), ('디저트_음료', '디저트 및 음료')], default='한식', max_length=20),
        ),
        migrations.AddField(
            model_name='post',
            name='location',
            field=models.CharField(choices=[('ECC', 'ECC'), ('조형대', '조형대'), ('공대', '공대'), ('연협', '연협'), ('학관', '학관'), ('학문관', '학문관'), ('중앙도서관', '중앙도서관')], default='ECC', max_length=20),
        ),
        migrations.AddField(
            model_name='post',
            name='pickup_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('모집중', '모집중'), ('모집완료', '모집완료')], default='모집중', max_length=10),
        ),
    ]
