# Generated by Django 5.2.12 on 2026-05-28 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SplitIt', '0005_remove_comment_username_comment_author_post_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='delivery_fee',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='min_order_amount',
            field=models.IntegerField(default=0),
        ),
    ]
